name: Deploy to Nexus and Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_run:
    workflows: [ "Merge develop into master" ]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install setuptools wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload to Nexus
        env:
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}
          REPOSITORY_USERNAME: ${{ vars.REPOSITORY_USERNAME }}
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
        run: |
          twine upload --repository-url $REPOSITORY_URL -u $REPOSITORY_USERNAME -p $REPOSITORY_PASSWORD dist/*

      - name: Tagging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "New tag: ${{ steps.get_version.outputs.VERSION }}"
          git tag -a "v${{ steps.get_version.outputs.VERSION }}" -m "Release v${{ steps.get_version.outputs.VERSION }}"
          git push --tags https://${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Prepare next version
        if: success()
        run: |
          git fetch --all
          git checkout develop
          python bump_version.py
          NEW_VERSION=$(grep '__version__' version.py | sed -e "s/__version__ = '\(.*\)'/\1/")
          git add version.py
          git commit -m "Prepare for next release version $NEW_VERSION"
          git push origin develop
